services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:4011"
    networks:
      - e-commerce-frontend
      - e-commerce-backend
    depends_on:
      auth-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      product-service:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: base
    secrets:
      - jwt_secret
    networks:
      - e-commerce-frontend
    
  auth-service:
    build:
      context: ./services/auth-service
      target: base
    secrets:
      - jwt_secret
    depends_on:
      mongodb-e-commerce :
        condition: service_healthy
    networks:
      - e-commerce-backend
      - e-commerce-db
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/api/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

  order-service:
    build:
      context: ./services/order-service
      target: base
    secrets:
      - jwt_secret
    depends_on:
      mongodb-e-commerce:
        condition: service_healthy
    networks:
      - e-commerce-backend
      - e-commerce-db
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3002/api/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

  product-service:
    build:
      context: ./services/product-service
      target: base
    secrets:
      - jwt_secret
    depends_on:
      mongodb-e-commerce:
        condition: service_healthy
    networks:
      - e-commerce-backend
      - e-commerce-db
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

  mongodb-e-commerce:
    image: mongo:4.4.30-focal
    networks:
      - e-commerce-db
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  e-commerce-frontend:
    driver: bridge
  e-commerce-backend:
    driver: bridge
  e-commerce-db:
    driver: bridge

secrets:
  jwt_secret:
    file: ./jwt_secret.txt

volumes:
  mongodb_data: