services:
  auth-service:
    build:
      context: ./auth-service
      target: base
    ports:
      - "4012:${PORT:-3001}"
    depends_on:
      - mongodb-e-commerce
    networks:
      - e-commerce
    secrets:
      - jwt_secret

  order-service:
    build:
      context: ./order-service
      target: base
    ports:
      - "4014:${PORT:-3002}"
    depends_on:
      - mongodb-e-commerce
    networks:
      - e-commerce
    secrets:
      - jwt_secret

  product-service:
    build:
      context: ./product-service
      target: base
    ports:
      - "4015:${PORT:-3000}"
    depends_on:
      - mongodb-e-commerce
    networks:
      - e-commerce
    secrets:
      - jwt_secret

  mongodb-e-commerce:
    image: mongo:4.4.30-focal
    ports:
      - "4013:27017"
    networks:
      - e-commerce
  
networks:
  e-commerce:
    driver: bridge

secrets:
  jwt_secret:
    file: ./jwt_secret.txt