services:
  auth-service:
    build:
      context: ./auth-service
      target: prod
    env_file: "auth-service/.env.production"
    secrets:
      - jwt_secret
      
  order-service:
    build:
      context: ./order-service
      target: prod
    env_file: "order-service/.env.production"
    secrets:
      - jwt_secret

secrets:
  jwt_secret:
    file: ./jwt_secret.prod.txt
