services:
  auth-service:
    build:
      context: .
      target: base
    ports:
      - "4012:${PORT:-3001}"
    depends_on:
      - mongodb-e-commerce
    networks:
      - e-commerce
  
  mongodb-e-commerce:
    image: mongo:4.4.30-focal
    ports:
      - "4013:27017"
    networks:
      - e-commerce
  
networks:
  e-commerce:
    driver: bridge