services:
  auth-service:
    build:
      context: .
      target: dev
    volumes:
      - "/app/node_modules"
      - ".:/app"
    env_file: ".env"
    secrets:
      - jwt_secret
  
secrets:
  jwt_secret:
    file: ./jwt_secret.txt