name: CI/CD Pipeline E-Commerce

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion au GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build des tests
        run: docker compose build --build-arg TARGET=test

      - name: Build et Push des images
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            docker compose -f docker-compose.yml -f docker-compose.prod.yml build
            docker compose -f docker-compose.yml -f docker-compose.prod.yml push
          else
            docker compose build
            docker compose push
          fi

      - name: Scan Frontend
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'ghcr.io/williammcorreia/e-commerce-frontend:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan Auth Service
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'ghcr.io/williammcorreia/e-commerce-auth-service:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan Order Service
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'ghcr.io/williammcorreia/e-commerce-order-service:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan Product Service
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'ghcr.io/williammcorreia/e-commerce-product-service:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan Reverse Proxy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'ghcr.io/williammcorreia/e-commerce-reverse-proxy:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'